# Generated by Django 6.1 on 2026-09-14 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0004_centrocosto_lineaasiento_centro_costo'),
        ('finanzas', '0001_initial'),
        ('lotes', '0005_lote_documento_liquidacion'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('fecha_embarque', models.DateField(blank=True, null=True)),
                ('pais_destino', models.CharField(max_length=100)),
                ('puerto_destino', models.CharField(blank=True, max_length=150)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - En fábrica'), ('FCA', 'FCA - Franco transportista'), ('FOB', 'FOB - Franco a bordo'), ('CFR', 'CFR - Costo y flete'), ('CIF', 'CIF - Costo, seguro y flete'), ('DAP', 'DAP - Entregado en lugar')], default='FOB', max_length=3)),
                ('peso_total', models.DecimalField(decimal_places=2, help_text='Kilos embarcados.', max_digits=12)),
                ('moneda', models.CharField(default='USD', editable=False, max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('EMBARCADA', 'Embarcada'), ('LIQUIDADA', 'Liquidada'), ('COBRADA', 'Cobrada'), ('CERRADA', 'Cerrada')], default='PREPARACION', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(help_text='Cliente internacional (tercero de tipo COMPRADOR).', on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones', to='terceros.tercero')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lote_comercial', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exportacion', to='lotes.lotecomercial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportación',
                'verbose_name_plural': 'Exportaciones',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CostoExportacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('FLETE', 'Flete'), ('SEGURO', 'Seguro'), ('ADUANA', 'Gastos de Aduana'), ('INSPECCION', 'Inspección / Supervisión'), ('ANALISIS', 'Análisis de Laboratorio'), ('PUERTO', 'Gastos Portuarios'), ('REGALIA', 'Regalías / Impuestos'), ('OTRO', 'Otro')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_exportacion', to='contabilidad.centrocosto')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(blank=True, help_text='Egreso real que respalda este costo, si ya fue pagado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costo_exportacion', to='finanzas.movimientofinanciero')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_exportacion', to='terceros.tercero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='exportaciones.exportacion')),
            ],
            options={
                'verbose_name': 'Costo de Exportación',
                'verbose_name_plural': 'Costos de Exportación',
                'ordering': ['-fecha'],
            },
        ),
    ]
