# Generated by Django 6.1 on 2026-08-24 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_creación', models.DateField()),
                ('peso_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTO', 'abierto'), ('CERRRADO', 'cerrado')], default='ABIERTO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote Comercial',
                'verbose_name_plural': 'Lotes Comerciales',
                'ordering': ['-fecha_creación'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('tipo_material', models.CharField(choices=[('ZINC', 'Zinc'), ('PLOMO', 'Plomo'), ('PLATA', 'Plata'), ('OTRO', 'Otro')], max_length=10)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tara', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=12)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_MUESTREO', 'En Muestreo'), ('EN_ANALISIS', 'En Análisis'), ('NEGOCIACION', 'En Negociación'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='terceros.tercero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('lote_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_internos', to='lotes.lotecomercial')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
