# Generated by Django 6.1 on 2026-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotecomercial',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Lote Comercial', 'verbose_name_plural': 'Lotes Comerciales'},
        ),
        migrations.RenameField(
            model_name='lotecomercial',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_MUESTREO', 'En Muestreo'), ('EN_ANALISIS', 'En Análisis'), ('NEGOCIACION', 'En Negociación'), ('LIQUIDADO', 'Liquidado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=12),
        ),
        migrations.AlterField(
            model_name='lote',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lotecomercial',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10),
        ),
    ]
