# Generated by Django 6.1 on 2026-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_poblar_tipos_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='documento_liquidacion',
            field=models.FileField(blank=True, null=True, upload_to='liquidaciones/%Y/%m/'),
        ),
    ]
