# Generated by Django 6.1 on 2026-08-25 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('lotes', '0005_lote_documento_liquidacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_negociacion', models.DateField()),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dolares')], default='USD', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('NEGOCIACION', 'En Negociacion'), ('LIQUIDADA', 'Liquidada'), ('PAGO_PARCIAL', 'Con Pago Parcial'), ('PAGADA', 'Pagada Totalmente'), ('CERRADA', 'Cerrada')], default='NEGOCIACION', max_length=15)),
                ('condiciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='lotes.lote')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_negociacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo_origen', models.CharField(choices=[('Anticipo', 'Aplicacion de Anticipo'), ('MOVIMIENTO', 'PAgo Directo (Movimiento Financiero)')], max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('aplicacion_anticipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_compra', to='finanzas.aplicacionanticipo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_aplicados', to='compras.compra')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compra',
                'ordering': ['-fecha'],
            },
        ),
    ]
