# Generated by Django 6.1 on 2026-09-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='liquidacion',
            field=models.OneToOneField(blank=True, help_text='Si se asocia una liquidacion, los valores se toman de ella.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='liquidaciones.liquidacion'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='movimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_compra', to='finanzas.movimientofinanciero'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='tipo_origen',
            field=models.CharField(choices=[('ANTICIPO', 'Aplicacion de Anticipo'), ('MOVIMIENTO', 'Pago Directo (Movimiento Financiero)')], max_length=12),
        ),
    ]
