# Generated by Django 6.1 on 2026-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_poblar_elementos'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='unidad_ley',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('GRAMO_TONELADA', 'Gramos por tonelada (g/t)'), ('ONZA_TONELADA', 'Onzas troy por tonelada (oz/t)')], default='PORCENTAJE', help_text='Unidad en que se reporta la ley de este elemento. Zn/Pb suelen ir en %, Ag/Au en g/t u oz/t.', max_length=20),
        ),
    ]
