# Generated by Django 6.1 on 2026-08-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_caja_options_alter_cuentabancaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
    ]
