# Generated by Django 6.1 on 2026-09-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_configuracioncontable_asiento_automatico_and_more'),
        ('organizacion', '0003_alter_caja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta del plan contable que representa este saldo. Necesaria para generar asientos automaticos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_asociadas', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta del plan contable que representa este saldo. Necesaria para generar asientos automaticos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias_asociadas', to='contabilidad.cuentacontable'),
        ),
    ]
