# Generated by Django 6.1 on 2026-09-14 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('lotes', '0005_lote_documento_liquidacion'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=10)),
                ('condiciones', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/%Y/%m/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='terceros.tercero')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato Comercial',
                'verbose_name_plural': 'Contratos Comerciales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('LOCAL', 'Venta Local'), ('REVENTA', 'Reventa de Material')], default='LOCAL', max_length=10)),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Kilos vendidos.', max_digits=12)),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('estado', models.CharField(choices=[('NEGOCIACION', 'En Negociación'), ('CONFIRMADA', 'Confirmada'), ('COBRO_PARCIAL', 'Con Cobro Parcial'), ('COBRADA', 'Cobrada Totalmente'), ('CERRADA', 'Cerrada')], default='NEGOCIACION', max_length=15)),
                ('condiciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='terceros.tercero')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.contratocomercial')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='lotes.lote')),
                ('lote_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='lotes.lotecomercial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CobroVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cobro_venta', to='finanzas.movimientofinanciero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cobro de Venta',
                'verbose_name_plural': 'Cobros de Venta',
                'ordering': ['-fecha'],
            },
        ),
    ]
