# Generated by Django 6.1 on 2026-09-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_configuracioncontable_asiento_automatico_and_more'),
        ('gastos', '0002_poblar_categorias_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto que se debita al registrar un gasto de esta categoria. Necesaria para el asiento automatico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_gasto', to='contabilidad.cuentacontable'),
        ),
    ]
