# Generated by Django 6.1 on 2026-08-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': ('Usuario',), 'verbose_name_plural': 'Usuarios'},
        ),
    ]
