# Generated by Django 6.1 on 2026-09-14 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio', '0003_elemento_unidad_ley'),
        ('lotes', '0005_lote_documento_liquidacion'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoDeduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concepto de Deducción',
                'verbose_name_plural': 'Conceptos de Deducción',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionMineral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad', models.CharField(choices=[('USD_TM', 'USD por tonelada métrica'), ('USD_OZT', 'USD por onza troy'), ('USD_LB', 'USD por libra')], default='USD_TM', max_length=10)),
                ('fuente', models.CharField(blank=True, help_text='De donde salio el precio (LME, London Fix, contrato, etc.)', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='laboratorio.elemento')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización de Mineral',
                'verbose_name_plural': 'Cotizaciones de Minerales',
                'ordering': ['-fecha', 'elemento'],
                'unique_together': {('elemento', 'fecha', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('BOB', 'Bolivianos')], default='USD', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('peso_humedo', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Kilos. Se copia del peso neto del lote.', max_digits=12)),
                ('humedad', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Porcentaje. Se copia de la muestra.', max_digits=5)),
                ('peso_seco', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='lotes.lote')),
                ('muestra', models.ForeignKey(help_text='Muestra cuyos resultados de ley se usan para el calculo.', on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='laboratorio.muestra')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DeduccionLiquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo_calculo', models.CharField(choices=[('MONTO_FIJO', 'Monto fijo'), ('PORCENTAJE', 'Porcentaje del valor bruto')], default='MONTO_FIJO', max_length=12)),
                ('valor', models.DecimalField(decimal_places=4, help_text='Monto en la moneda de la liquidacion, o porcentaje segun el tipo.', max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deducciones', to='liquidaciones.conceptodeduccion')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='liquidaciones.liquidacion')),
            ],
            options={
                'verbose_name': 'Deducción de Liquidación',
                'verbose_name_plural': 'Deducciones de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='ReglaLiquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('porcentaje_pagable', models.DecimalField(decimal_places=3, help_text='Porcentaje del contenido fino que se paga (ej. 85.000 para 85%).', max_digits=6)),
                ('ley_minima', models.DecimalField(decimal_places=4, default=0, help_text='Por debajo de esta ley el elemento no se paga.', max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_liquidacion', to='laboratorio.elemento')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Vacio = regla general para todos los proveedores.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_liquidacion', to='terceros.tercero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de Liquidación',
                'verbose_name_plural': 'Reglas de Liquidación',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ley', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad_ley', models.CharField(default='PORCENTAJE', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unidad_precio', models.CharField(default='USD_TM', max_length=10)),
                ('porcentaje_pagable', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ley_minima', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('contenido_fino', models.DecimalField(decimal_places=6, default=0, editable=False, help_text='En TM finas, u onzas troy si el elemento se mide en g/t u oz/t.', max_digits=16)),
                ('valor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='liquidaciones.cotizacionmineral')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='laboratorio.elemento')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='liquidaciones.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
                'unique_together': {('liquidacion', 'elemento')},
            },
        ),
    ]
