# Generated by Django 6.1 on 2026-09-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_ajustar_unidad_ley_metales'),
        ('liquidaciones', '0002_poblar_conceptos_deduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduccionliquidacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe resultante, calculado por el frontend.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='deduccionliquidacion',
            name='valor',
            field=models.DecimalField(decimal_places=4, help_text='El porcentaje aplicado, o el monto fijo pactado.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='contenido_fino',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Calculado por el frontend. En TM finas, u onzas troy segun el elemento.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='cotizacion',
            field=models.ForeignKey(blank=True, help_text='Cotizacion concreta que se uso, si salio del catalogo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='liquidaciones.cotizacionmineral'),
        ),
        migrations.AlterField(
            model_name='detalleliquidacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculado por el frontend: lo que se paga por este elemento.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='humedad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de humedad aplicado.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='muestra',
            field=models.ForeignKey(help_text='Muestra cuyos resultados de ley se usaron para el calculo.', on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='laboratorio.muestra'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='peso_humedo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilos, tal como se uso en el calculo.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='peso_seco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilos secos resultantes.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='total_deducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma del valor de todos los elementos pagables.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='valor_neto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor bruto menos deducciones. Es lo que se paga al proveedor.', max_digits=14),
        ),
    ]
