# Generated by Django 6.1.1 on 2026-09-14 22:00

import liquidaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_alter_deduccionliquidacion_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, editable=False, help_text='PDF generado por el sistema a partir de este registro.', null=True, upload_to=liquidaciones.models.ruta_pdf_liquidacion),
        ),
    ]
