# Generated by Django 6.1 on 2026-09-14 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_centrocosto_lineaasiento_centro_costo'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generar_asientos_automaticos', models.BooleanField(default=True, help_text='Si se desmarca, el sistema deja de generar asientos solo.')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuración Contable',
            },
        ),
        migrations.AddField(
            model_name='asiento',
            name='automatico',
            field=models.BooleanField(default=False, editable=False, help_text='Generado por el sistema a partir de una operacion.'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='origen_content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_originados', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='origen_object_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['origen_content_type', 'origen_object_id'], name='contabilida_origen__3ba09e_idx'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='anticipos_proveedores',
            field=models.ForeignKey(blank=True, help_text='Activo. Se debita al entregar un anticipo a un proveedor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_anticipos', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuentas_por_cobrar',
            field=models.ForeignKey(blank=True, help_text='Activo. Se debita al vender y se acredita al cobrar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_cxc', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='cuentas_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Pasivo. Se acredita al comprar y se debita al pagar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_cxp', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='egresos_varios',
            field=models.ForeignKey(blank=True, help_text='Gasto por defecto para egresos sin categoria ni documento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_egresos_varios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='ingresos_varios',
            field=models.ForeignKey(blank=True, help_text='Ingreso por defecto para movimientos de caja sin documento asociado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_ingresos_varios', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='inventario_mineral',
            field=models.ForeignKey(blank=True, help_text='Activo. Se debita al registrar una compra de mineral.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_inventario', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracioncontable',
            name='ventas',
            field=models.ForeignKey(blank=True, help_text='Ingreso. Se acredita al registrar una venta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_ventas', to='contabilidad.cuentacontable'),
        ),
    ]
