# Generated by Django 6.1 on 2026-08-21 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0003_alter_caja_options'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=3)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Aplicado Parcialmente'), ('APLICADO', 'Aplicado Totalmente'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='terceros.tercero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionAnticipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, help_text='Referencia a la compra/lote donde se aplicó (se vinculará formalmente en Fase 3)', max_length=255)),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='finanzas.anticipo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación de Anticipo',
                'verbose_name_plural': 'Aplicaciones de Anticipo',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('origen', models.CharField(choices=[('CAJA', 'Caja'), ('BANCO', 'Cuenta Bancaria')], max_length=10)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('fecha', models.DateField()),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='organizacion.caja')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='organizacion.cuentabancaria')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='terceros.tercero')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anticipo',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anticipo', to='finanzas.movimientofinanciero'),
        ),
        migrations.CreateModel(
            name='TransferenciaEntreCuentas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('origen_tipo', models.CharField(choices=[('CAJA', 'Caja'), ('BANCO', 'Cuenta Bancaria')], max_length=10)),
                ('destino_tipo', models.CharField(choices=[('CAJA', 'Caja'), ('BANCO', 'Cuenta Bancaria')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destino_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='organizacion.caja')),
                ('destino_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='organizacion.cuentabancaria')),
                ('origen_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='organizacion.caja')),
                ('origen_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='organizacion.cuentabancaria')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre Cuentas',
                'verbose_name_plural': 'Transferencias entre Cuentas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
